### ISSUE TITLE
New release with org.LatencyUtils.PauseDetector protected constructor

### ISSUE THREAD

**Issue by stanislav-kobylansky** [LatencyUtils/LatencyUtils#11]
Would be good to see release with protected org.LatencyUtils.PauseDetector constructor on maven central. Thx.

**Comment by asgs** [comment]
Looks the commit [Mark PauseDetector ctor protected](https://github.com/LatencyUtils/LatencyUtils/commit/12a5314519e120ccfc09d82d8a37382eec69bc4a) fulfilled the request. can be closed
